//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenJedi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrdenJediEntities : DbContext
    {
        public OrdenJediEntities()
            : base("name=OrdenJediEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Especies> Especies { get; set; }
        public virtual DbSet<Miembros> Miembros { get; set; }
        public virtual DbSet<Planetas> Planetas { get; set; }
        public virtual DbSet<Rangos> Rangos { get; set; }
        public virtual DbSet<RelJedisPadawans> RelJedisPadawans { get; set; }
        public virtual DbSet<RelMiembrosPlanetas> RelMiembrosPlanetas { get; set; }
        public virtual DbSet<Estatus> Estatus { get; set; }
    }
}
